name: fundfix
channels:
  - conda-forge
  - defaults
dependencies:
  - matplotlib=3.1.1
  - numpy=1.17.3
  - pandas=0.25.3
  - python=3.7.0
  - scipy=1.3.1
  - seaborn=0.9.0
  - shapely=1.6.4
  - pip:
    - arviz==0.7.0
    - bokeh==1.4.0
    - fiona
    - geopandas
    - pymc3==3.8
    - theano==1.0.4
    - voila==0.1.20
    - watermark==2.0.2
    - xarray==0.14.1