name: elections-models
channels:
  - conda-forge
  - defaults
dependencies:
  - arviz>=0.9
  - black
  - bokeh
  - fiona
  - geopandas
  - jupyterlab 
  - matplotlib
  - numpy
  - pandas
  - pymc3
  - python>=3.7
  - python-graphviz
  - scipy
  - shapely
  - theano>=1.0.4
  - voila
  - watermark
  - xarray
  - pip:
    - black_nbconvert